namespace Sudlife_ProtectShieldPlus.APILayer.API.Model
{
    public class SDEBaseResponse
    {
        public string? BIJson { get; set; }
        public string? BIJson2 { get; set; }
        public string? CHOICE_QUOTEID { get; set; }
        public List<InputValidationStatus>? InputValidationStatus { get; set; }
        public string? Message { get; set; }
        public string? PDFData { get; set; }
        public string? PDFURL { get; set; }
        public object? ProductCode { get; set; }
        public string? QuotationId { get; set; }
        public string? Status { get; set; }
        public string? Step { get; set; }
        public int TransactionId { get; set; }
    }

    public class InputValidationStatus
    {
        public int AgeMasterId { get; set; }
        public double AnnualPremium { get; set; }
        public string? EntryAge { get; set; }
        public List<object>? ErrorMessage { get; set; }
        public int FailedCount { get; set; }
        public string? GeneralError { get; set; }
        public List<object>? IpKeyword { get; set; }
        public List<object>? IpKwMessage { get; set; }
        public int LoadAnnPrems { get; set; }
        public string? MIError { get; set; }
        public string? MaturityAge { get; set; }
        public double ModalPremium { get; set; }
        public double ModeDisc { get; set; }
        public int ModeFreq { get; set; }
        public int MonthlyIncome { get; set; }
        public List<object>? OptionError { get; set; }
        public int PPT { get; set; }
        public int PT { get; set; }
        public string? Premium { get; set; }
        public int ProductId { get; set; }
        public string? RiderMessage { get; set; }
        public long SA { get; set; }
        public decimal SAMF { get; set; }
        public string? SAMFError { get; set; }
        public string? SumAssured { get; set; }
        public double Tax { get; set; }
        public int Tax_2 { get; set; }
        public string? UlipSA { get; set; }
    }

    public class BIJsonstr
    {
        public int PolicyYear { get; set; }
        public int LI_ATTAINED_AGE { get; set; }
        public string? UniqueKey { get; set; }
        public int POLICYTERM { get; set; }
        public int LOAN_JL_3 { get; set; }
        public int LOAN_JL_4 { get; set; }
        public int LOAN_AMOUNT { get; set; }
        public string? GENDER { get; set; }
        public double TAX_KFC { get; set; }
        public string? OPTION_NAME_1 { get; set; }
        public int MAX_MAT_AGE { get; set; }
        public int MAT_AGE { get; set; }
        public string? PREM_FUNDING { get; set; }
        public string? STAFF_POLICY { get; set; }
        public string? CI_T { get; set; }
        public int MAX_SA_OB { get; set; }
        public int FOURTH_AGE { get; set; }
        public int SECOND_AGE { get; set; }
        public string? LIFE_STATUS { get; set; }
        public int THIRD_AGE { get; set; }
        public string? COV_TYPE { get; set; }
        public string? GENDER_2 { get; set; }
        public string? GENDER_3 { get; set; }
        public string? GENDER_4 { get; set; }
        public int SHARE_PERCENT { get; set; }
        public int FLAG { get; set; }
        public double SHARE_LA_PB { get; set; }
        public int LOAN_CAT { get; set; }
        public int SHARE_PERCENT_2 { get; set; }
        public string? OPTION_NAME { get; set; }
        public string? TOTAL_LOAN_PERIOD { get; set; }
        public int SHARE_PERCENT_3 { get; set; }
        public int CI_TERM { get; set; }
        public int CI_TERM_2 { get; set; }
        public int BEN_OP { get; set; }
        public string? LOAN_TYPE { get; set; }
        public double SA_1 { get; set; }
        public int SHARE_PERCENT_4 { get; set; }
        public string? MORA_OPTION { get; set; }
        public string? JL_OPTION { get; set; }
        public int MORA_PERIOD { get; set; }
        public double SHARE_LA_SB { get; set; }
        public string? INT_RATE { get; set; }
        public string? BEN_TYPE { get; set; }
        public double SHARE_LA_TB { get; set; }
        public double SHARE_LA_FB { get; set; }
        public double TAXRATE_FINAL { get; set; }
        public string? INT_RATE_2 { get; set; }
        public string? PREM_CONC { get; set; }
        public string? ADB_ATPD_CONC { get; set; }
        public string? PREM_CONC_2 { get; set; }
        public string? PREM_CONC_4 { get; set; }
        public string? PREM_CONC_3 { get; set; }
        public string? ACI_CONC { get; set; }
        public string? ACI_CONC_2 { get; set; }
        public string? ACI_CONC_4 { get; set; }
        public string? ACI_CONC_3 { get; set; }
        public double PREMIUMRATE_ADB { get; set; }
        public double PREMIUMRATE_ATPD { get; set; }
        public double PREMIUMRATE { get; set; }
        public double PREMIUMRATE_ADB_2 { get; set; }
        public double PREMIUMRATE_ADB_4 { get; set; }
        public double PREMIUMRATE_ATPD_4 { get; set; }
        public double PREMIUMRATE_ATPD_2 { get; set; }
        public double PREMIUMRATE_ADB_3 { get; set; }
        public double PREMIUMRATE_ATPD_3 { get; set; }
        public double PREMIUMRATE_4 { get; set; }
        public double PREMIUMRATE_2 { get; set; }
        public double PREMIUMRATE_3 { get; set; }
        public double PREMIUMRATE_ACI { get; set; }
        public double PREMIUMRATE_ACI_4 { get; set; }
        public double PREMIUMRATE_ACI_2 { get; set; }
        public double PREMIUMRATE_ACI_3 { get; set; }
        public double ADJ_PR_ADB { get; set; }
        public double ADJ_PR_ATPD { get; set; }
        public double ADJ_PREMIUMRATE { get; set; }
        public double FACTOR { get; set; }
        public double ADJ_PR_ADB_2 { get; set; }
        public double ADJ_PR_ADB_4 { get; set; }
        public double ADJ_PR_ATPD_2 { get; set; }
        public double ADJ_PR_ATPD_4 { get; set; }
        public double ADJ_PR_ADB_3 { get; set; }
        public double ADJ_PR_ATPD_3 { get; set; }
        public double ADJ_PREMIUMRATE_4 { get; set; }
        public double ADJ_PREMIUMRATE_2 { get; set; }
        public double ADJ_PREMIUMRATE_3 { get; set; }
        public double FACTOR_4 { get; set; }
        public double FACTOR_2 { get; set; }
        public double FACTOR_3 { get; set; }
        public double ADJ_PR_ACI { get; set; }
        public double ADJ_PR_ACI_4 { get; set; }
        public double ADJ_PR_ACI_2 { get; set; }
        public double ADJ_PR_ACI_3 { get; set; }
        public double RATE_SUM { get; set; }
        public double RATE_SUM_4 { get; set; }
        public double RATE_SUM_2 { get; set; }
        public double RATE_SUM_3 { get; set; }
        public double FACTOR_ATPD { get; set; }
        public int CONDITION { get; set; }
        public double FACTOR_ATPD_4 { get; set; }
        public double FACTOR_ATPD_2 { get; set; }
        public double FACTOR_ATPD_3 { get; set; }
        public int CONDITION_2 { get; set; }
        public int CONDITION_4 { get; set; }
        public int CONDITION_3 { get; set; }
        public double VALUE { get; set; }
        public double FLAG_2 { get; set; }
        public double LOAN_JL { get; set; }
        public double LOAN_JL_2 { get; set; }
        public double LOAN_IND { get; set; }
        public double LOAN_IND_2 { get; set; }
        public double LOAN_IND_4 { get; set; }
        public double SA4 { get; set; }
        public double SHARE_AMOUNT_4 { get; set; }
        public double LOAN_IND_3 { get; set; }
        public double SA3 { get; set; }
        public double SHARE_AMOUNT_3 { get; set; }
        public double PREMIUM_WO_REBATE_4 { get; set; }
        public double INST_PREM_4 { get; set; }
        public double PREMIUM_WO_REBATE_3 { get; set; }
        public double INST_PREM_3 { get; set; }
        public double SA { get; set; }
        public double PREMIUM_WO_REBATE { get; set; }
        public double INST_PREM { get; set; }
        public double SA2 { get; set; }
        public double PREMIUM_WO_REBATE_2 { get; set; }
        public double INST_PREM_2 { get; set; }
        public double SA_AMOUNT_2 { get; set; }
        public double SA_BEN_4 { get; set; }
        public double SA_ADB_4 { get; set; }
        public double SA_BEN_3 { get; set; }
        public double SA_ADB_3 { get; set; }
        public double ADB_PREM_WO_REBATE_4 { get; set; }
        public double ATPD_PREM_WO_REBATE_4 { get; set; }
        public double INST_PREM_ADB_4 { get; set; }
        public double ACI_PREM_WO_REBATE_4 { get; set; }
        public double ADB_PREM_WO_REBATE_3 { get; set; }
        public double ATPD_PREM_WO_REBATE_3 { get; set; }
        public double INST_PREM_ADB_3 { get; set; }
        public double ACI_PREM_WO_REBATE_3 { get; set; }
        public double SA_BEN { get; set; }
        public double SA_ADB { get; set; }
        public double ADB_PREM_WO_REBATE { get; set; }
        public double ATPD_PREM_WO_REBATE { get; set; }
        public double INST_PREM_ADB { get; set; }
        public double ACI_PREM_WO_REBATE { get; set; }
        public double SA_BEN_2 { get; set; }
        public double SA_ADB_2 { get; set; }
        public double ADB_PREM_WO_REBATE_2 { get; set; }
        public double ATPD_PREM_WO_REBATE_2 { get; set; }
        public double INST_PREM_ADB_2 { get; set; }
        public double ACI_PREM_WO_REBATE_2 { get; set; }
        public double TOT_INST_PREM { get; set; }
        public double GST { get; set; }
        public double INST_PREM_B_4 { get; set; }
        public double INST_PREM_B_3 { get; set; }
        public double FINAL_INST_PREM { get; set; }
        public double TOTAL_PREM_4 { get; set; }
        public double JL_REBATE_4 { get; set; }
        public double TOTAL_PREM_3 { get; set; }
        public double JL_REBATE_3 { get; set; }
        public double INST_PREM_B { get; set; }
        public double INST_PREM_B_2 { get; set; }
        public double TOTAL_PREM { get; set; }
        public double JL_REBATE { get; set; }
        public double TOTAL_PREM_2 { get; set; }
        public double JL_REBATE_2 { get; set; }
        public double TOT_INST_PREM_ADB { get; set; }
        public double GST_ADB { get; set; }
        public double STAFF_REBATE_4 { get; set; }
        public double STAFF_REBATE_3 { get; set; }
        public double STAFF_REBATE { get; set; }
        public double STAFF_REBATE_2 { get; set; }
        public double FINAL_INST_PREM_ADB { get; set; }
        public double SINGLE_PREM_4 { get; set; }
        public double SINGLE_PREM_3 { get; set; }
        public double TOT_INST_PREM_B { get; set; }
        public double GST_B { get; set; }
        public double SINGLE_PREM { get; set; }
        public double SINGLE_PREM_2 { get; set; }
        public double GST_TOT { get; set; }
        public double FINAL_INST_PREM_B { get; set; }
        public double TOTAL_SINGLE_PREM_WITH_GST { get; set; }
        public double ANN_PREM { get; set; }
        public double MODAL_PREM { get; set; }
        public double LOAD_ANN_PREM { get; set; }
        public double TAX_MP { get; set; }
        public double TOTAL_SINGLE_PREM_WO_GST { get; set; }
        public double MODAL_PREM_TAX { get; set; }
    }
}
